export enum Primitive {
    STRING,
    NUMBER,
    BIGINT,
    BOOLEAN,
    NULL,
    UNDEFINED,
    SYMBOL
}

export enum Typeof {
    UNDEFINED = 'undefined',
    BOOLEAN = 'boolean',
    NUMBER = 'number',
    BIGINT = 'bigint',
    STRING = 'string',
    SYMBOL = 'symbol',
    FUNCTION = 'function',
    ANY_OTHER = 'object',
}

export enum Operator {
    ADDITION,
    SUBTRACTION,
    MULTIPLICATION,
    DIVISION,
    MODULUS,
    INCREMENT,
    DECREMENT,
    EQUALS,
    ADDITION_EQUALS,
    SUBTRACTION_EQUALS,
    MULTIPLICATION_EQUALS,
    DIVISION_EQUALS,
    MODULUS_EQUALS,
    EQUAL_TO,
    EQUAL_VALUE_AND_EQUAL_TYPE,
    NOT_EQUAL,
    NOT_EQUAL_VALUE_OR_NOT_EQUAL_TYPE,
    GREATER_THAN,
    LESS_THAN,
    GREATER_THAN_OR_EQUAL_TO,
    LESS_THAN_OR_EQUAL_TO,
    CONDITION,
    LOGICAL_AND,
    LOGICAL_OR,
    NOT,
    BITWISE_AND,
    BITWISE_OR,
    BITWISE_NOT,
    XOR,
    LEFT_SHIFT,
    RIGHT_SHIFT,
    TYPEOF,
    DELETE,
    IN,
    INSTANCEOF,
    VOID
}

export enum KeyCode {
    BACKSPACE = 8,
    TAB = 9,
    ENTER = 13,
    SHIFT = 16,
    CTRL = 17,
    ALT = 18,
    PAUSE_BREAK = 19,
    CAPS_LOCK = 20,
    ESCAPE = 27,
    PAGE_UP = 33,
    SPACE = 33,
    PAGE_DOWN = 34,
    END = 35,
    HOME = 36,
    LEFT_ARROW = 37,
    UP_ARROW = 38,
    RIGHT_ARROW = 39,
    DOWN_ARROW = 40,
    PRINT_SCREEN = 44,
    INSERT = 45,
    DELETE = 46,
    ZERO = 48,
    ONE = 49,
    TWO = 50,
    THREE = 51,
    FOUR = 52,
    FIVE = 53,
    SIX = 54,
    SEVEN = 55,
    EIGHT = 56,
    NINE = 57,
    A = 65,
    B = 66,
    C = 67,
    D = 68,
    E = 69,
    F = 70,
    G = 71,
    H = 72,
    I = 73,
    J = 74,
    K = 75,
    L = 76,
    M = 77,
    N = 78,
    O = 79,
    P = 80,
    Q = 81,
    R = 82,
    S = 83,
    T = 84,
    U = 85,
    V = 86,
    W = 87,
    X = 88,
    Y = 89,
    Z = 90,
    LEFT_WINDOW_KEY = 91,
    RIGHT_wINDOW_KEY = 92,
    SELECT = 93,
    NUMPAD_ZERO = 96,
    NUMPAD_ONE = 97,
    NUMPAD_TWO = 98,
    NUMPAD_THREE = 99,
    NUMPAD_FOUR = 100,
    NUMPAD_FIVE = 101,
    NUMPAD_SIX = 102,
    NUMPAD_SEVEN = 103,
    NUMPAD_EIGHT = 104,
    NUMPAD_NINE = 105,
    MULTIPLY = 106,
    ADD = 107,
    SUBTRACT = 109,
    DECIMAL_POINT = 110,
    DIVIDE = 111,
    F1 = 112,
    F2 = 113,
    F3 = 114,
    F4 = 115,
    F5 = 116,
    F6 = 117,
    F7 = 118,
    F8 = 119,
    F9 = 120,
    F10 = 121,
    F11 = 122,
    F12 = 123,
    NUM_LOCK = 144,
    SCROLL_LOCK = 145,
    MY_COMPUTER = 182,
    MY_CALCULATOR = 183,
    SEMI_COLON = 186,
    EQUAL_SIGN = 187,
    COMMA = 188,
    DASH = 189,
    PERIOD = 190,
    FORWARD_SLASH = 191,
    OPEN_BRACKET = 219,
    BACK_SLASH = 220,
    CLOSE_BRACKET = 221,
    SINGLE_QUOTE = 222,
}